### ISSUE TITLE
LaTeX Error: File 'main-style .tex' not found

### ISSUE THREAD

**Issue by hdchan** [CuriousLearner/jdf-latex#8]
After a fresh install of [MacTeX 2020](https://tug.org/mactex/mactex-download.html) on MacOSX 10.15.16 (Catalina), and running the `make` command on a newly initialized JDF project I received the following error: `LaTeX Error: File 'main-style .tex' not found`. This hasn't happened to me on my previous Macbooks, but something must have caused the white spaces surrounding the [main-style](https://github.com/CuriousLearner/jdf-latex/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/main.tex#L1) input to be interpreted as a part of the file name.

**Comment by CuriousLearner** [comment]
Yeah, it wasn't happening earlier, but seems like recent tex installation in mac has this issue. 

Can you raise a PR with that commit? I'll be happy to merge it in :)

**Comment by CuriousLearner** [comment]
Fixed in #9
